version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - back
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"